export { default as HomePage } from './home.page';
export { default as SearchPage } from './search.page';
export { default as FavoritePage } from './favorite.page';
export { default as CollectionPage } from './collection.page';
export { default as SignInPage } from './signIn.page';
export { default as SignUpPage } from './signUp.page';
export { default as TracksPage } from './tracks.page';
export { default as ShowAllPage } from './showAll.page';
export { default as NotFoundPage } from './notFound.page';
